### ISSUE TITLE
cfn_delete consistently fails

### ISSUE THREAD

**Issue by lgarvey** [ministryofjustice/bootstrap-cfn#177]
CF output: 

11:54:19 UTC+0000   DELETE_FAILED   AWS::EC2::VPCGatewayAttachment  AttachGateway   Network vpc-69a8810c has some mapped public address(es). Please unmap those public address(es) before detaching the gateway.

pip freeze tells me: 

bootstrap-cfn==0.7.5

If I manually find the IGW and detach it, then I can delete the stack.

**Comment by mattpep** [comment]
Though I mostly get this error, once in a while (say 1 out of 5, perhaps a little less often) I've had a stack successfully delete. I suspect this is related to the speed of some operations, and on the occasions a stack _has_ deleted, it's been because an ordinarily slow operation has completed before the depending VPC deleted.

The core work of the cfn_delete task is a single call (source file `bootstrap_cfn/cloudformation.py`, class method `delete`) to the boto library. So we can't resolve this at deletion time, but we can prevent the issue from cropping up by changing what we do at creation time. Advice found at http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/troubleshooting.html#troubleshooting-errors-delete-stack-fails includes:

> To resolve a dependency error, add a DependsOn attribute to resources that depend on other resources in your template.

Once the fix is in place, we'll still have this issue on stacks which have been created in the period between after the problematic VPC was added[1] and before that problematic VPC had its dependency added. But future stacks will be deletable without problem.

[1] Identifying this VPC is the crux of this issue

**Comment by mattpep** [comment]
Our AWS Solutions Architect provided the following input:

> I believe it may be due to a missing DependsOn in your CF template. The most common cause for this is when you have an EIP without an explicit DependsOn to the Internet Gateway.  Looking at your template specifically, it seems like the Auto Scaling Launch Configuration (which specifies that instances get a public IP) should have “DependOn” : “AttachGateway”, so that the InternetGateway is created and attached before the instances launch with public Ips. 
> See here: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-dependson.html#gatewayattachment

**Comment by filipposc5** [comment]
fixed by #214
