### ISSUE TITLE
Not waiting for instances in scaling groups.

### ISSUE THREAD

**Issue by mattmb** [ministryofjustice/bootstrap-cfn#30]
It seems that cloud formation reports scaling groups as 'complete' before the instances have finished running anything in their launch configuration. Ideally we don't want cloud formation to report complete until the instances have finished launching.

[This](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html#d0e11716) or [this](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-signal.html) seem to be the answer but I didn't have any luck last week.

**Comment by stuartornum** [comment]
Because we've created an auto-scaling group (which could have zero instances as its default) cloudformation is acting how it is meant to.

What I've done before to get around this is once the stack has "COMPETED" is to check if you can SSH to the instances, and retry on failure.

I'm guessing this is all about getting salt stuff on the box?

**Comment by mattmb** [comment]
Yeah, that's what I figured. SSH not being up that was the reason I spotted this, so we could just check for it being up. Have you ever used the cfn-signal stuff? I guess the problem is that you don't know how many instances need to check in to say they're complete...

**Comment by stuartornum** [comment]
I wouldnt use signals for this because: The idea with our CFN is that you create the stack for say dev once, then at 22:00 we scale down the instances to zero, then at 07:00 we scale it up again, so if we have signals with the instances it's just going to confuse things - easier to just wait for SSH to come up.

**Comment by mattmb** [comment]
I think you're right. We need to think a bit more about how we bootstrap instances when we use ASGs. It would be cool if any new instances bootstrapped themselves and highstated themself etc.
